# Generated by Django 2.1.4 on 2018-12-11 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=30),
        ),
    ]
