# Generated by Django 2.1.4 on 2018-12-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0002_auto_20181211_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='keywords',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
