# Generated by Django 2.1.4 on 2018-12-17 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0004_auto_20181217_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletin.Source'),
        ),
        migrations.AlterField(
            model_name='item',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletin.Source'),
        ),
    ]
