# Generated by Django 2.1.4 on 2018-12-17 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0005_auto_20181217_0209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='source',
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.ManyToManyField(blank=True, to='bulletin.Source'),
        ),
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.ManyToManyField(blank=True, to='bulletin.Source'),
        ),
    ]
