# Generated by Django 2.1.4 on 2018-12-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0006_auto_20181217_0213'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='source',
        ),
        migrations.AddField(
            model_name='feed',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.RemoveField(
            model_name='item',
            name='source',
        ),
        migrations.AddField(
            model_name='item',
            name='source',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
