# Generated by Django 2.1.4 on 2018-12-18 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0008_auto_20181217_0217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keywords', models.CharField(blank=True, max_length=200, null=True)),
                ('numitems', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletin.Story'),
        ),
    ]
