# Generated by Django 2.1.4 on 2019-02-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0011_category_topkeys'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='topkeyvals',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
