# Generated by Django 2.1.4 on 2019-02-27 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0015_topic_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='topics',
            field=models.ManyToManyField(blank=True, to='bulletin.Topic'),
        ),
    ]
