# Generated by Django 2.1.4 on 2019-02-27 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0016_profile_topics'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='user',
        ),
    ]
