# Generated by Django 2.1.4 on 2019-02-27 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0017_remove_topic_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='lead',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='story',
            name='leadlink',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
