# Generated by Django 2.1.4 on 2019-02-27 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0018_auto_20190227_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='bulletin.Story'),
        ),
        migrations.AlterField(
            model_name='story',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='categories', to='bulletin.Category'),
        ),
    ]
