# Generated by Django 2.1.4 on 2019-02-28 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0020_auto_20190228_0206'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='leadsource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bulletin.Source'),
        ),
    ]
