# Generated by Django 2.1.4 on 2019-02-28 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0021_story_leadsource'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='keys_factor',
            field=models.CharField(default='2', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='words_factor',
            field=models.CharField(default='3', max_length=10),
        ),
    ]
