# Generated by Django 2.1.4 on 2019-03-01 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0022_auto_20190228_0420'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stocks',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
