# Generated by Django 2.1.4 on 2019-03-03 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0024_auto_20190302_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='elapsed_hours',
            field=models.IntegerField(default=24),
        ),
    ]
