# Generated by Django 2.1.4 on 2019-03-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0026_auto_20190303_0159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='score',
        ),
        migrations.AddField(
            model_name='item',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='item',
            name='elapsed_hours',
            field=models.IntegerField(default=48),
        ),
    ]
