# Generated by Django 2.1.4 on 2019-03-04 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0028_auto_20190303_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='allwords',
            field=models.CharField(blank=True, max_length=5500),
        ),
        migrations.AlterField(
            model_name='story',
            name='image',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
