# Generated by Django 2.1.4 on 2019-03-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0029_auto_20190304_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='numkeys',
            field=models.SmallIntegerField(default=0),
        ),
    ]
