# Generated by Django 2.1.4 on 2019-03-06 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0032_auto_20190305_0406'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='catorder',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
