# Generated by Django 2.1.4 on 2019-03-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0035_auto_20190307_0201'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='slug',
            field=models.CharField(blank=True, max_length=600),
        ),
        migrations.AlterField(
            model_name='item',
            name='desc',
            field=models.CharField(max_length=600),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('US/Eastern', 'US/Eastern'), ('US/Central', 'US/Central'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific')], max_length=40, null=True),
        ),
    ]
