# Generated by Django 2.1.4 on 2019-03-12 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0036_auto_20190309_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='filter_words',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
