# Generated by Django 2.1.4 on 2019-03-14 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0038_category_skip_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='weathercities',
            field=models.CharField(default='[]', max_length=150),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('US/Eastern', 'US/Eastern'), ('US/Central', 'US/Central'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific')], default='US/Eastern', max_length=40, null=True),
        ),
    ]
