# Generated by Django 2.1.4 on 2019-03-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0039_auto_20190314_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stocks',
            field=models.CharField(blank=True, default='[]', max_length=300),
        ),
    ]
