# Generated by Django 2.1.4 on 2019-03-20 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0041_profile_emailtimes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
