# Generated by Django 2.1.4 on 2019-03-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0042_auto_20190320_1636'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='emailtimes',
        ),
        migrations.AddField(
            model_name='profile',
            name='emaildaytimes',
            field=models.CharField(default='[]', max_length=1000),
        ),
        migrations.AddField(
            model_name='profile',
            name='emailformdata',
            field=models.CharField(default='[{}]', max_length=1000),
        ),
    ]
