# Generated by Django 2.1.4 on 2019-04-05 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0045_source_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_filter',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
