# Generated by Django 2.1.4 on 2019-04-16 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0051_userstory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstory',
            name='score',
            field=models.DecimalField(decimal_places=10, max_digits=30, null=True),
        ),
    ]
