# Generated by Django 2.1.4 on 2019-04-20 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0053_feed_catdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='skip_list',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
