# Generated by Django 2.1.4 on 2019-04-20 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0054_feed_skip_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='skip_list',
            field=models.CharField(default='[]', max_length=2000),
        ),
    ]
