# Generated by Django 2.1.4 on 2019-04-27 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0056_auto_20190421_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='topkeys',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='topkeyvals',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
