# Generated by Django 2.1.4 on 2019-04-29 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0057_auto_20190427_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='new_story',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='story',
            name='to_delete',
            field=models.BooleanField(default=False),
        ),
    ]
