# Generated by Django 2.1.4 on 2019-05-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0059_source_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='numitems',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
