# Generated by Django 2.1.4 on 2019-06-27 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bulletin', '0061_auto_20190518_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstemail',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='catorder',
            field=models.CharField(blank=True, default="['Politics', 'Business', 'Custom topics', 'International']", max_length=1000),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stocks',
            field=models.CharField(blank=True, default="['DIA', 'SPY', 'QQQ']", max_length=300),
        ),
        migrations.AlterField(
            model_name='profile',
            name='timezone',
            field=models.CharField(choices=[('US/Eastern', 'US/Eastern'), ('US/Central', 'US/Central'), ('US/Mountain', 'US/Mountain'), ('US/Pacific', 'US/Pacific')], default='US/Pacific', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weathercities',
            field=models.CharField(default="['Portland, OR']", max_length=150),
        ),
    ]
